# Generated by Django 5.1.7 on 2025-05-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_eventtype_id_alter_menu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='dietary_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='menu',
            name='price_per_guest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
