# Generated by Django 3.1.12 on 2025-05-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_menu_categories_menu_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
